'use client'

import Image from 'next/image'
import { FC, Fragment, useState } from 'react'
import { SvgCaret } from '../../../../components/Icons'
import {
  DietModification,
  GeneData,
  GeneModification,
  mobGenetics,
  reverseMobDiets,
  reverseMobGenetics,
} from '../../../../data/mobGenetics'

const geneticsByMobId = 'genetics-by-id'
const geneticsByDietId = 'genetics-by-diet'
const geneticsByGeneId = 'genetics-by-gene'

export default function MobGeneticsPage() {
  const [indexCollapsed, setIndexCollapsed] = useState(true)

  return (
    <div className="mx-auto flex max-w-7xl flex-row px-4 sm:px-6 lg:px-8">
      <div
        className={
          (indexCollapsed ? 'w-0 -translate-x-4' : 'w-64') +
          ' sticky top-20 mb-10 h-[calc(100vh-6rem)] shrink-0 transition-all'
        }
      >
        <div className="relative h-full rounded-xl border border-white/5 bg-surface-900">
          <button
            onClick={() => setIndexCollapsed(!indexCollapsed)}
            aria-label={indexCollapsed ? 'Expand index' : 'Collapse index'}
            className="absolute -right-8 top-2 z-50 flex h-8 w-8 items-center justify-center text-ink-400 hover:text-ink-100"
          >
            <SvgCaret
              className={
                'h-6 transition-transform ' +
                (indexCollapsed ? '-rotate-90' : 'rotate-90')
              }
            />
          </button>
          <div className="dumbcode-scrollbar h-full overflow-y-auto rounded-xl">
            <MobGeneticsIndex />
          </div>
        </div>
      </div>

      <div className="m-10 flex min-w-0 flex-grow flex-col">
        <h1 className="text-4xl font-semibold text-ink-100">Genetics Guide</h1>
        <p className="pt-2 text-ink-300">
          This guide shows you the genetics generated by different mobs.
        </p>
        <MobGeneticsByMob />
        <MobGeneticsByDiet />
        <MobGeneticsByGene />
      </div>
    </div>
  )
}

const MobGeneticsIndex = () => {
  return (
    <div className="mx-5 my-4 text-ink-200">
      <h2 className="text-2xl font-semibold text-ink-100">Index</h2>

      <CollapsableIndex id={geneticsByMobId} title="Genetics By Mob" maxHeightClass="max-h-[1000px]">
        {mobGenetics.map((genetics, i) => (
          <a key={i} href={`#${formatEntity(genetics)}`} className="hover:text-brand-300">
            {genetics.name}
          </a>
        ))}
      </CollapsableIndex>

      <CollapsableIndex id={geneticsByDietId} title="Genetics By Diet" maxHeightClass="max-h-[200px]">
        {Array.from(reverseMobDiets.keys()).sort().map((diet, i) => (
          <a key={i} href={`#${formatDiet(diet)}`} className="hover:text-brand-300">
            {diet}
          </a>
        ))}
      </CollapsableIndex>

      <CollapsableIndex id={geneticsByGeneId} title="Genetics By Gene" maxHeightClass="max-h-[500px]">
        {Array.from(reverseMobGenetics.keys()).sort().map((gene, i) => (
          <a key={i} href={`#${formatGene(gene)}`} className="hover:text-brand-300">
            {gene}
          </a>
        ))}
      </CollapsableIndex>
    </div>
  )
}

const CollapsableIndex: FC<{
  id: string
  title: string
  maxHeightClass: string
  children?: React.ReactNode
}> = ({ id, title, children, maxHeightClass }) => {
  const [collapsed, setCollapsed] = useState(true)
  return (
    <div className="border-b border-white/5 p-1 last:border-none">
      <div className="flex flex-row items-center">
        <a href={`#${id}`}>{title}</a>
        <button
          onClick={() => setCollapsed(!collapsed)}
          className={'ml-2 transition-transform ' + (collapsed ? '-rotate-90' : '')}
        >
          <SvgCaret className="w-3" />
        </button>
      </div>
      <div
        className={
          'ml-5 flex flex-col overflow-hidden transition-[max-height] ' +
          (collapsed ? 'max-h-0' : maxHeightClass)
        }
      >
        {children}
      </div>
    </div>
  )
}

const MobGeneticsByMob = () => {
  return (
    <div className="mt-5">
      <a id={geneticsByMobId} href={`#${geneticsByMobId}`} className="text-3xl font-semibold text-ink-100">
        Genetics By Mob
      </a>
      <div className="grid xl:grid-cols-2 2xl:grid-cols-3">
        {mobGenetics.map((geneData, i) => (
          <MobGeneticEntry key={i} geneData={geneData} />
        ))}
      </div>
    </div>
  )
}

type ColourData = { colours: string[]; varient?: string }

const MobGeneticEntry = ({ geneData }: { geneData: GeneData }) => {
  const id = formatEntity(geneData)
  const colourData = geneData.colours.reduce<ColourData[]>(
    (array, colour) => {
      if (typeof colour === 'string') {
        array[0].colours.push(colour)
      } else {
        array.push({
          colours: typeof colour.colour === 'string' ? [colour.colour] : colour.colour,
          varient: colour.varient,
        })
      }
      return array
    },
    [{ colours: [] }]
  )

  return (
    <div className="mx-2 mt-10 rounded-xl border border-white/5 bg-surface-900 p-4">
      <a href={`#${id}`} id={id} className="text-2xl font-semibold text-ink-100">
        {geneData.name}
      </a>
      <div className="flex flex-row">
        <div className="relative mr-2 mt-2 h-32 w-32 shrink-0">
          <Image
            alt={`Entity ${geneData.name}`}
            fill
            sizes="128px"
            className="object-contain"
            src={`/images/guides/genetics/${geneData.image}`}
          />
        </div>
        <div className="flex flex-grow flex-col">
          {geneData.geneModifications.length !== 0 && (
            <div className="mb-2">
              <h4 className="text-lg font-semibold text-ink-100">Genes:</h4>
              {geneData.geneModifications.map((g, i) => (
                <MobGeneModificationEntry key={i} modification={g} />
              ))}
            </div>
          )}
          {geneData.dietModifications !== undefined &&
            geneData.dietModifications.length !== 0 && (
              <div className="mb-2">
                <h4 className="text-lg font-semibold text-ink-100">Diet Changes:</h4>
                <div className="flex flex-row">
                  {geneData.dietModifications.map((diet, i) => (
                    <MobDietModificationEntry key={i} diet={diet} />
                  ))}
                </div>
              </div>
            )}
          {colourData.length !== 0 && (
            <div className="mb-2">
              <h4 className="text-lg font-semibold text-ink-100">Colors:</h4>
              <div className="flex w-full flex-row flex-wrap pr-10">
                {colourData
                  .filter((c) => c.colours.length !== 0)
                  .map((colour, i) => (
                    <MobColourCell key={i} colour={colour} />
                  ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

const MobGeneModificationEntry = ({ modification }: { modification: GeneModification }) => {
  const positive = modification.amount > 0
  return (
    <div className="flex flex-row">
      <a href={`#${formatGene(modification.gene)}`} className="text-ink-200">
        {modification.gene}:
      </a>
      <span className={(positive ? 'text-green-400' : 'text-red-400') + ' ml-2'}>
        {positive ? '+' : '-'}
        {Math.round(Math.abs(modification.amount) * 100)}%
      </span>
    </div>
  )
}

const MobDietModificationEntry = ({ diet }: { diet: DietModification }) => {
  return (
    <div className="mr-10 flex flex-col text-ink-200">
      <a href={`#${formatDiet(diet.name)}`} className="font-semibold text-ink-100">
        {diet.name}
      </a>
      <div className="relative mr-2 mt-2 h-16 w-16">
        <Image
          alt={`Diet ${diet.name}`}
          fill
          sizes="64px"
          className="object-contain"
          src={`/images/guides/genetics/${diet.image}`}
        />
      </div>
      <span className="text-blue-400">+{diet.water} Water</span>
      <span className="text-amber-400">+{diet.food} Food</span>
    </div>
  )
}

const MobColourCell = ({ colour }: { colour: ColourData }) => {
  return (
    <div className="group relative">
      <div className="relative m-1 h-8 w-8 flex-row overflow-hidden rounded-full border border-black">
        <div className="absolute z-0 flex h-full w-full flex-row rounded-full">
          {colour.colours.map((c, i) => (
            <div className="flex-grow" key={i} style={{ backgroundColor: c }} />
          ))}
        </div>
      </div>
      {colour.varient && (
        <div className="absolute z-50 hidden rounded-md bg-surface-900 p-1 text-xs font-semibold text-ink-100 group-hover:inline-block">
          {colour.varient}
        </div>
      )}
    </div>
  )
}

const MobGeneticsByDiet = () => {
  return (
    <div className="mt-5">
      <a id={geneticsByDietId} href={`#${geneticsByDietId}`} className="text-3xl font-semibold text-ink-100">
        Genetics By Diet
      </a>
      <div className="grid xl:grid-cols-2 2xl:grid-cols-3">
        {Array.from(reverseMobDiets.keys())
          .sort()
          .map((key) => {
            const dietInfo = reverseMobDiets.get(key)
            if (!dietInfo) return <Fragment key={key} />
            return <MobGeneticsByDietEntry key={key} name={key} data={dietInfo} />
          })}
      </div>
    </div>
  )
}

const MobGeneticsByDietEntry = ({
  name,
  data,
}: {
  name: string
  data: {
    image: string
    data: { mob: GeneData; diet: DietModification }[]
  }
}) => {
  const id = formatDiet(name)
  return (
    <div className="mx-2 mt-10 flex flex-col rounded-xl border border-white/5 bg-surface-900 p-4">
      <a href={`#${id}`} id={id} className="text-2xl font-semibold text-ink-100">
        {name}
      </a>
      <div className="flex w-full flex-row">
        <div className="relative mr-2 mt-2 h-32 w-32">
          <Image
            alt={`Diet ${data.image}`}
            fill
            sizes="128px"
            className="object-contain"
            src={`/images/guides/genetics/${data.image}`}
          />
        </div>
        {data.data.map((info, i) => (
          <div key={i} className="mr-5 flex flex-col">
            <a href={`#${formatEntity(info.mob)}`} className="font-semibold text-ink-200">
              {info.mob.name}
            </a>
            <span className="text-blue-400">+{info.diet.water} Water</span>
            <span className="text-amber-400">+{info.diet.food} Food</span>
          </div>
        ))}
      </div>
    </div>
  )
}

const MobGeneticsByGene = () => {
  return (
    <div className="mt-5">
      <a id={geneticsByGeneId} href={`#${geneticsByGeneId}`} className="text-3xl font-semibold text-ink-100">
        Genetics By Gene
      </a>
      {Array.from(reverseMobGenetics.keys())
        .sort()
        .map((key) => {
          const geneInfo = reverseMobGenetics.get(key)
          if (!geneInfo) return <Fragment key={key} />
          return <MobGeneticsByGeneEntry key={key} name={key} data={geneInfo} />
        })}
    </div>
  )
}

const MobGeneticsByGeneEntry = ({
  name,
  data,
}: {
  name: string
  data: { data: GeneData; amount: number }[]
}) => {
  const id = formatGene(name)
  return (
    <div className="mx-2 mt-10 flex flex-col rounded-xl border border-white/5 bg-surface-900 p-4">
      <a href={`#${id}`} id={id} className="text-2xl font-semibold text-ink-100">
        {name}
      </a>
      {data.map((datum, i) => {
        const positive = datum.amount > 0
        return (
          <div key={i} className="flex flex-row">
            <a href={`#${formatEntity(datum.data)}`} className="text-ink-200">
              {datum.data.name}:
            </a>
            <span className={(positive ? 'text-green-400' : 'text-red-400') + ' ml-2'}>
              {positive ? '+' : '-'}
              {Math.round(Math.abs(datum.amount) * 100)}%
            </span>
          </div>
        )
      })}
    </div>
  )
}

const formatEntity = (entity: GeneData) =>
  `entity-${entity.name.replace(/\s/g, '-').toLowerCase()}`
const formatDiet = (diet: string) => `diet-${diet.replace(/\s/g, '-').toLowerCase()}`
const formatGene = (gene: string) => `gene-${gene.replace(/\s/g, '-').toLowerCase()}`
